spring.application.name=invoice-application-backend

# Database
spring.datasource.url=jdbc:postgresql://candidate-tracker-db.postgres.database.azure.com:5432/invoice_db?sslmode=require
spring.datasource.username=candidatetrackeradmin
spring.datasource.password=IRay@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=subbutadi36@gmail.com
spring.mail.password=eoxi povy icki wopt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.company.name=I-Ray IT Solutions
app.company.address=Madhapur
app.company.email=subbutadi36@gmail.com
app.company.approved-for-f-tax=true

app.mail.from-name=I-Ray Invoicing
app.mail.from-address=subbutadi36@gmail.com
app.frontend-base-url=${FRONTEND_BASE_URL}

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true